Fix #3: avoid TypeError exception when no int subset
When a DOCTYPE is matched but no internal subset, the result
of the match object's match['IntSubset'] is None.

This leads to a TypeError exception:

   TypeError: argument of type 'NoneType' is not iterable

If no internal subset could be found, continue with next
file. This avoids the above error.

* Raise version to 2.1.0
* Added integration tests with "real" XML files and output
* Use .group() on match object to be compatible with Python 3.5
  (match object is only scriptable on Python >=3.6)